apiVersion: v1
kind: ConfigMap
metadata:
  name: masterv2-api-configmap-dev
  namespace: sit
data:
  #AppVersion: 6.0.0.0
  DataProvider: PostgreSql
  DataConnectionString: Host=192.168.1.100:5433;Database=postgres;Username=duy;Password=123;Pooling=True;Minimum Pool Size=1;Maximum Pool Size=1024;Multiplexing=False
