apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-car-serv-car-serv-deployment
  name: car-serv-deployment
  namespace: ecommerce
spec:
  replicas: 2
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-car-serv-car-serv-deployment
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-car-serv-car-serv-deployment
      namespace: ecommerce
    spec:
      containers:
        - image: elroydevops/car-serv
          imagePullPolicy: Always
          name: car-serv
          ports:
            - containerPort: 80
              name: tcp
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: car-serv1-service
  namespace: ecommerce
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-car-serv-car-serv-deployment
  sessionAffinity: None
  type: ClusterIP
---  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production  # Sử dụng ClusterIssuer
  name: car-serv-ingress
  namespace: ecommerce
spec:
  tls:
    - hosts:
        - car-serv-onpre.devopsedu.vn  # Tên miền của bạn
      secretName: car-tls  # Tên Secret sẽ được tạo
  rules:
    - host: car-serv-onpre.devopsedu.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: car-serv1-service
                port:
                  number: 80


            
