apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
  labels:
    app: docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-app
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
        - name: docker-app
          image: docker.io/duy290410/tmc:001
          #image: tripotadevacr.azurecr.io/apihub-frontend-react:15491
          port : 
            - containerPort : 8888
          imagePullPolicy: Always   
      imagePullSecrets:
        - name: dockerhub-acr-secret   
