apiVersion: v1
kind: Secret
metadata:
  name: tmc-secret
type: Opaque
stringData:
  .dockerconfigjson: |
    [
      {
        "auths": {
          "https://hub.docker.com/r/duy290410/tmc/tags": {
            "auth": "ZHV5MjkwNDEwOmRja3JfcGF0X1FWVzNma09Ya1pJYmZPU2NYOHdSaHJTNHV5dw=="
          }
        }
      }
    ]