apiVersion: v1
kind: Service
metadata:
  name: masterv2-api-dev-svc
  namespace: sit
spec:
  selector:
    app: masterv2-api-dev
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
