#apiVersion: v1
#kind: Service
#metadata:
#  name: docker-app-svc
#  #namespace: master
#spec:
#  selector:
#    app: docker-app
#  ports:
#    - name: http
#      protocol: TCP
#      port: 80
#      targetPort: 8888
#  type: ClusterIP
